import Foundation

enum LocalizationCatalog {
    static let supplementalTranslations: [String: [String: String]] = [
        "en": [
            "settings.language": "Language",
            "settings.language.system": "System",
            "assumptions.paychecks_per_year_label": "Paychecks per year",
            "common.ok": "OK",
            "common.edit": "Edit",
            "common.done": "Done",
            "objects.custom.image_picker": "Choose image",
            "objects.custom.change_image": "Change image",
            "objects.custom.image_hint": "Pick a photo from your library. It will be cropped into a square icon.",
            "objects.custom.image_error_title": "Image unavailable",
            "objects.custom.image_error": "Couldn't load this image. Try a different photo.",
            "objects.custom.save_error": "Couldn't save this image on your device.",
            "objects.custom.manage_title": "Edit Custom Objects",
            "objects.custom.manage_hint": "Drag to reorder. Swipe left or tap Delete to remove an object.",
            "objects.custom.edit_title": "Edit Object",
            "objects.custom.update": "Update Object"
        ],
        "ru": [
            "settings.language": "Язык",
            "settings.language.system": "Как в системе",
            "settings.appearance": "Внешний вид",
            "settings.theme": "Тема",
            "settings.reduce_motion": "Уменьшить анимацию",
            "settings.haptics": "Тактильный отклик",
            "settings.high_contrast": "Высокий контраст",
            "common.edit": "Изменить",
            "common.done": "Готово",
            "settings.defaults": "По умолчанию",
            "settings.default_currency": "Базовая валюта",
            "settings.income_basis": "Тип дохода",
            "settings.dataset_info": "О наборе данных",
            "settings.version": "Версия",
            "settings.cities_bundled": "Городов в наборе",
            "settings.objects_bundled": "Объектов в наборе",
            "settings.dataset_note": "Индексы по городам и ценам на предметы — это локальные статичные ориентиры. Они помогают уточнить допущения, а не изображают абсолютную экономическую истину.",
            "settings.privacy": "Конфиденциальность",
            "settings.privacy_note": "Earnza полностью работает офлайн. Без аккаунта, без трекинга и без зависимости от серверов для основного продукта.",
            "salary_input.annual": "В год",
            "salary_input.monthly": "В месяц",
            "salary_input.weekly": "В неделю",
            "salary_input.hourly": "В час",
            "salary_input.currency": "Валюта",
            "salary_input.input_mode": "Режим ввода",
            "salary_input.based_on": "На основе режима «%@» и сохранённых рабочих допущений.",
            "salary_input.edit_assumptions": "Изменить допущения",
            "income_basis.gross": "До вычета налогов",
            "income_basis.take_home": "На руки",
            "theme.light": "Светлая",
            "theme.dark": "Тёмная",
            "theme.solar": "Solar",
            "theme.mono": "Mono",
            "canvas.live": "Live",
            "canvas.objects": "Объекты",
            "canvas.work": "Работа",
            "canvas.cities": "Города",
            "canvas.gap": "Разрыв",
            "header.scenario": "Сценарии",
            "header.share": "Поделиться",
            "header.settings": "Настройки",
            "assumption.hours": "Часы",
            "assumption.weeks": "Недели",
            "assumption.rent": "Аренда",
            "assumption.comparator": "Сравнение",
            "assumption.city": "Город",
            "assumption.basis": "База",
            "pace.per_month": "В месяц",
            "pace.per_day": "В день",
            "pace.per_hour": "В час",
            "pace.per_minute": "В минуту",
            "pace.per_second": "В секунду",
            "pace.per_workday": "За рабочий день",
            "pace.per_paycheck": "За выплату",
            "common.off": "Выкл.",
            "common.unset": "Не задано",
            "common.scenario_value": "Сценарий: %@",
            "common.currency_value": "Валюта: %@",
            "common.exact_value": "Точное значение: %@",
            "common.price_value": "Цена: %@",
            "common.share_card": "Поделиться карточкой",
            "common.currency": "Валюта",
            "common.ok": "ОК",
            "share.default.subtitle": "Столько вы зарабатываете за минуту.",
            "share.default.hourly_pace": "Темп в час: %@",
            "share.default.monthly_pace": "Темп в месяц: %@",
            "share.default.assumptions": "На основе %@ ч/нед и %@ нед/год",
            "live.title": "Смотрите, как доход становится видимым.",
            "live.subtitle": "Непрерывный темп, накопление за сессию чтения и внятные моменты для шаринга.",
            "live.earning_now": "Вы зарабатываете прямо сейчас",
            "live.real_time_note": "Пока вы это читаете, сумма продолжает расти в реальном времени.",
            "live.minute_pace": "Темп в минуту",
            "live.while_you_read_this": "Пока вы это читаете",
            "live.screen_session": "Накопление за сессию",
            "live.per_minute_value": "В минуту: %@",
            "live.per_hour_value": "В час: %@",
            "live.per_second_subtitle": "Непрерывная скорость для живого счётчика",
            "live.per_minute_subtitle": "Самый наглядный ритм в реальном времени",
            "live.per_workday_subtitle": "С учётом сохранённых рабочих допущений",
            "live.per_paycheck_subtitle": "На основе количества выплат в год",
            "live.per_month_subtitle": "Зарплата, разложенная на 12 месяцев",
            "live.reading_session": "Сессия чтения",
            "live.reading_session_subtitle": "Сбрасывается, когда приложение снова становится активным",
            "live.milestones": "Вехи",
            "live.cross_milestone": "Преодолейте %@ за эту сессию.",
            "objects.title": "Переведите зарплату в реальные вещи.",
            "objects.subtitle": "Предметы остаются редактируемыми, локальными и готовыми к шарингу.",
            "objects.mode": "Режим",
            "objects.mode.how_many": "Сколько можно",
            "objects.mode.work_for_it": "Сколько работать",
            "objects.add_custom": "Добавить свой объект",
            "objects.quantity_note": "Сколько вы зарабатываете при текущем темпе.",
            "objects.favorite": "В избранное",
            "objects.per_hour": "%@ в час",
            "objects.per_day": "В день: %@",
            "objects.workdays": "%@ раб. дней",
            "objects.hours": "%@ ч",
            "objects.hero_earn": "Вы зарабатываете %@ %@ в час.",
            "objects.hero_work": "Один %@ стоит %@ рабочих часов.",
            "objects.share.work_subtitle": "Сколько нужно работать, чтобы это купить.",
            "objects.custom.title": "Свой объект",
            "objects.custom.name": "Название",
            "objects.custom.price": "Цена",
            "objects.custom.sf_symbol": "SF Symbol",
            "objects.custom.image_picker": "Выбрать изображение",
            "objects.custom.change_image": "Сменить изображение",
            "objects.custom.image_hint": "Фото возьмётся из медиатеки и будет обрезано до квадратной иконки.",
            "objects.custom.image_error_title": "Изображение недоступно",
            "objects.custom.image_error": "Не удалось загрузить это изображение. Попробуйте другое фото.",
            "objects.custom.save_error": "Не удалось сохранить изображение на устройстве.",
            "objects.custom.manage_title": "Свои объекты",
            "objects.custom.manage_hint": "Перетаскивайте для смены порядка. Смахните влево или нажмите Delete, чтобы удалить объект.",
            "objects.custom.edit_title": "Изменить объект",
            "objects.custom.update": "Обновить объект",
            "objects.custom.save": "Сохранить объект",
            "objects.custom.default_name": "Свой объект",
            "objects.custom.supporting_line": "Пользовательский ориентир для сравнения с зарплатой.",
            "work.title": "Почувствуйте цену в часах труда.",
            "work.subtitle": "Временные дорожки превращают цену в реальное усилие.",
            "work.share.title": "Столько вы работаете ради",
            "work.share.subtitle": "%@ часов работы",
            "cities.subtitle": "Локальные редакционные индексы, а не обещания точности по налогам.",
            "cities.search": "Поиск города или страны",
            "cities.sort": "Сортировка",
            "cities.pin": "Закрепить",
            "cities.stretch_score": "Индекс растяжки %@",
            "cities.daily_power_value": "Покупательная сила в день: %@",
            "cities.burger_pace": "Бургеров в час: %@",
            "cities.pressure_index": "Индекс давления: %@",
            "cities.daily_power": "Покупательная сила в день: %@",
            "cities.housing_pressure": "Жилищная нагрузка: %@",
            "cities.tech_affordability_score": "Доступность техники: %@",
            "cities.big_mac_pace": "Big Mac в час: %@",
            "cities.affordability": "Доступность",
            "cities.method": "Метод",
            "cities.method_note": "Статичный локальный набор данных. Редакционные индексы накладываются на ваш сохранённый сценарий без притворной налоговой точности.",
            "cities.share_city_card": "Поделиться карточкой города",
            "gap.subtitle": "Жёстко, по фактам и пригодно для шаринга без дешёвой драматизации.",
            "gap.comparator_pace": "Темп сравнения",
            "gap.comparator_pace_subtitle": "Относительная скорость минута к минуте",
            "gap.they_earn_your_hour_in": "Они зарабатывают ваш час за",
            "gap.they_earn_your_hour_in_subtitle": "Сжатый перевод разницы во времени",
            "gap.delta_per_hour": "Разница в час",
            "gap.delta_per_hour_subtitle": "Разрыв при одинаковых рабочих допущениях",
            "gap.ladder": "Лестница разрыва",
            "gap.ladder_body": "%@ зарабатывает эквивалент %@ PS5-часов экономии за каждый час работы.",
            "gap.empty_title": "Добавьте зарплату для сравнения в допущениях, чтобы открыть этот экран.",
            "gap.empty_body": "Используйте его для босса, другого оффера, целевой зарплаты или любого бенчмарка, с которым хотите сравнивать свой текущий темп.",
            "gap.share.title": "Темп сравнения",
            "gap.share.subtitle": "%@ против вашего текущего сценария",
            "gap.share.annual": "Годовой доход для сравнения: %@",
            "gap.share.delta": "Разница в час: %@",
            "gap.share.minutes": "Они зарабатывают ваш час за %@ минут",
            "library.title": "Библиотека сценариев",
            "library.current": "Текущий",
            "library.archive": "В архив",
            "library.duplicate": "Дублировать",
            "library.compare": "Сравнить",
            "library.city_rent": "Город: %@  Аренда: %@",
            "library.delta_annual": "Разница: %@ в год",
            "library.rent_difference": "Разница по аренде: %@ в месяц",
            "scenario.current_role": "Текущая роль",
            "scenario.manager": "Менеджер",
            "scenario.comparator": "Сравнение",
            "scenario.new": "Новый сценарий",
            "scenario.copy_format": "Копия %@",
            "share.title": "Share Studio",
            "share.template": "Шаблон",
            "share.privacy": "Приватность",
            "share.export_card": "Экспортировать карточку",
            "share.export_note": "Экспорт изображения использует нативный рендеринг с активной темой и выбранным режимом приватности.",
            "share_privacy.exact": "Точно",
            "share_privacy.blurred": "Размыто",
            "share_privacy.hidden": "Скрыто",
            "share_privacy.hidden_value": "Скрыто",
            "share_template.bold_number": "Крупное число",
            "share_template.comparison_split": "Сравнение пополам",
            "share_template.city_ranking": "Рейтинг городов",
            "share_template.object_statement": "Объект как тезис",
            "share_template.work_time": "Время работы",
            "share_template.summary_set": "Набор сводок",
            "assumptions.calculation_basis": "База расчёта",
            "assumptions.manual_take_home_annual": "Годовой доход на руки вручную",
            "assumptions.hours_per_week": "Часов в неделю",
            "assumptions.weeks_per_year": "Недель в году",
            "assumptions.paychecks_per_year": "Выплат в год: %@",
            "assumptions.paychecks_per_year_label": "Выплат в год",
            "assumptions.work_schedule": "График работы",
            "assumptions.monthly_rent": "Аренда в месяц",
            "assumptions.comparator_salary": "Годовая зарплата для сравнения",
            "assumptions.comparator_label": "Подпись сравнения",
            "assumptions.home_city": "Базовый город",
            "assumptions.lifestyle_inputs": "Бытовые параметры",
            "onboarding.page1.title": "Поймите, что реально значит ваша зарплата.",
            "onboarding.page1.subtitle": "Переводите доход во время, предметы, аренду и повседневный контекст.",
            "onboarding.page1.stat": "$0.43 / мин",
            "onboarding.page1.label": "Кофе за 18.4 минуты",
            "onboarding.page2.title": "Узнайте, сколько вещи стоят по-настоящему.",
            "onboarding.page2.subtitle": "Переведите любую покупку в часы вашей жизни.",
            "onboarding.page2.stat": "6.2 ч",
            "onboarding.page2.label": "PS5 стоит вам 6.2 часа работы",
            "onboarding.page3.title": "Сравните зарплату в 50 городах.",
            "onboarding.page3.subtitle": "Поймите, где та же сумма тянется дальше.",
            "onboarding.page3.stat": "в 3 раза дальше",
            "onboarding.page3.label": "Та же зарплата: Остин против Сан-Франциско",
            "onboarding.page4.title": "Приватность по умолчанию.",
            "onboarding.page4.subtitle": "Все расчёты остаются на вашем устройстве. Аккаунт не нужен.",
            "onboarding.page4.stat": "100% локально",
            "onboarding.page4.label": "Ни один байт не уходит с устройства",
            "onboarding.cta.finish": "Перевести мою зарплату",
            "work_desc.coffee_break": "Меньше, чем кофейный перерыв",
            "work_desc.lunch_stretch": "Примерно как длинный обед",
            "work_desc.focus_block": "Часть сфокусированного рабочего блока",
            "work_desc.half_day": "Примерно полдня работы",
            "work_desc.more_than_day": "Больше одного полного дня",
            "work_desc.week": "Почти рабочая неделя",
            "work_desc.serious_chunk": "Серьёзный кусок рабочего времени",
            "city_comparison.stretches_further": "Здесь зарплата тянется дальше.",
            "city_comparison.feels_tighter": "Здесь по ощущениям теснее.",
            "city_comparison.saved_assumptions": "На основе сохранённых допущений."
        ]
    ]
}

extension Scenario {
    static var localizedStarterName: String {
        L10n.s("scenario.current_role", "Current Role")
    }

    static var localizedStarterComparator: String {
        L10n.s("scenario.manager", "Manager")
    }

    static var localizedComparatorFallback: String {
        L10n.s("scenario.comparator", "Comparator")
    }

    static var localizedNewScenarioName: String {
        L10n.s("scenario.new", "New Scenario")
    }

    static func localizedDuplicateName(from name: String) -> String {
        L10n.f("scenario.copy_format", "%@ Copy", name)
    }
}
