import Foundation

enum LocalizationCatalog {
    static let supplementalTranslations: [String: [String: String]] = [
        "en": [
            "settings.language": "Language",
            "settings.language.system": "System",
            "assumptions.paychecks_per_year_label": "Paychecks per year",
            "common.ok": "OK",
            "common.edit": "Edit",
            "common.done": "Done",
            "objects.custom.image_picker": "Choose image",
            "objects.custom.change_image": "Change image",
            "objects.custom.image_hint": "Pick a photo from your library. It will be cropped into a square icon.",
            "objects.custom.image_error_title": "Image unavailable",
            "objects.custom.image_error": "Couldn't load this image. Try a different photo.",
            "objects.custom.save_error": "Couldn't save this image on your device.",
            "objects.custom.manage_title": "Edit Custom Objects",
            "objects.custom.manage_hint": "Drag to reorder. Swipe left or tap Delete to remove an object.",
            "objects.custom.edit_title": "Edit Object",
            "objects.custom.update": "Update Object"
        ],
        "ru": [
            "settings.language": "Язык",
            "settings.language.system": "Как в системе",
            "settings.appearance": "Внешний вид",
            "settings.theme": "Тема",
            "settings.reduce_motion": "Уменьшить анимацию",
            "settings.haptics": "Тактильный отклик",
            "settings.high_contrast": "Высокий контраст",
            "common.edit": "Изменить",
            "common.done": "Готово",
            "settings.defaults": "По умолчанию",
            "settings.default_currency": "Базовая валюта",
            "settings.income_basis": "Тип дохода",
            "settings.dataset_info": "О наборе данных",
            "settings.version": "Версия",
            "settings.cities_bundled": "Городов в наборе",
            "settings.objects_bundled": "Объектов в наборе",
            "settings.dataset_note": "Индексы по городам и ценам на предметы — это локальные статичные ориентиры. Они помогают уточнить допущения, а не изображают абсолютную экономическую истину.",
            "settings.privacy": "Конфиденциальность",
            "settings.privacy_note": "Earnza полностью работает офлайн. Без аккаунта, без трекинга и без зависимости от серверов для основного продукта.",
            "salary_input.annual": "В год",
            "salary_input.monthly": "В месяц",
            "salary_input.weekly": "В неделю",
            "salary_input.hourly": "В час",
            "salary_input.currency": "Валюта",
            "salary_input.input_mode": "Режим ввода",
            "salary_input.based_on": "На основе режима «%@» и сохранённых рабочих допущений.",
            "salary_input.edit_assumptions": "Изменить допущения",
            "income_basis.gross": "До вычета налогов",
            "income_basis.take_home": "На руки",
            "theme.light": "Светлая",
            "theme.dark": "Тёмная",
            "theme.solar": "Solar",
            "theme.mono": "Mono",
            "canvas.live": "Live",
            "canvas.objects": "Объекты",
            "canvas.work": "Работа",
            "canvas.cities": "Города",
            "canvas.gap": "Разрыв",
            "header.scenario": "Сценарии",
            "header.share": "Поделиться",
            "header.settings": "Настройки",
            "assumption.hours": "Часы",
            "assumption.weeks": "Недели",
            "assumption.rent": "Аренда",
            "assumption.comparator": "Сравнение",
            "assumption.city": "Город",
            "assumption.basis": "База",
            "pace.per_month": "В месяц",
            "pace.per_day": "В день",
            "pace.per_hour": "В час",
            "pace.per_minute": "В минуту",
            "pace.per_second": "В секунду",
            "pace.per_workday": "За рабочий день",
            "pace.per_paycheck": "За выплату",
            "common.off": "Выкл.",
            "common.unset": "Не задано",
            "common.scenario_value": "Сценарий: %@",
            "common.currency_value": "Валюта: %@",
            "common.exact_value": "Точное значение: %@",
            "common.price_value": "Цена: %@",
            "common.share_card": "Поделиться карточкой",
            "common.currency": "Валюта",
            "common.ok": "ОК",
            "share.default.subtitle": "Столько вы зарабатываете за минуту.",
            "share.default.hourly_pace": "Темп в час: %@",
            "share.default.monthly_pace": "Темп в месяц: %@",
            "share.default.assumptions": "На основе %@ ч/нед и %@ нед/год",
            "live.title": "Смотрите, как доход становится видимым.",
            "live.subtitle": "Непрерывный темп, накопление за сессию чтения и внятные моменты для шаринга.",
            "live.earning_now": "Вы зарабатываете прямо сейчас",
            "live.real_time_note": "Пока вы это читаете, сумма продолжает расти в реальном времени.",
            "live.minute_pace": "Темп в минуту",
            "live.while_you_read_this": "Пока вы это читаете",
            "live.screen_session": "Накопление за сессию",
            "live.per_minute_value": "В минуту: %@",
            "live.per_hour_value": "В час: %@",
            "live.per_second_subtitle": "Непрерывная скорость для живого счётчика",
            "live.per_minute_subtitle": "Самый наглядный ритм в реальном времени",
            "live.per_workday_subtitle": "С учётом сохранённых рабочих допущений",
            "live.per_paycheck_subtitle": "На основе количества выплат в год",
            "live.per_month_subtitle": "Зарплата, разложенная на 12 месяцев",
            "live.reading_session": "Сессия чтения",
            "live.reading_session_subtitle": "Сбрасывается, когда приложение снова становится активным",
            "live.milestones": "Вехи",
            "live.cross_milestone": "Преодолейте %@ за эту сессию.",
            "objects.title": "Переведите зарплату в реальные вещи.",
            "objects.subtitle": "Предметы остаются редактируемыми, локальными и готовыми к шарингу.",
            "objects.mode": "Режим",
            "objects.mode.how_many": "Сколько можно",
            "objects.mode.work_for_it": "Сколько работать",
            "objects.add_custom": "Добавить свой объект",
            "objects.quantity_note": "Сколько вы зарабатываете при текущем темпе.",
            "objects.favorite": "В избранное",
            "objects.per_hour": "%@ в час",
            "objects.per_day": "В день: %@",
            "objects.workdays": "%@ раб. дней",
            "objects.hours": "%@ ч",
            "objects.minutes": "%@ мин",
            "objects.work_months": "%@ раб. мес.",
            "objects.work_years": "%@ раб. лет",
            "objects.hero_earn": "Вы зарабатываете %@ %@ в час.",
            "objects.hero_work": "Один %@ стоит %@ рабочих часов.",
            "objects.hero_work_duration": "Один %@ ≈ %@ работы.",
            "objects.share.work_subtitle": "Сколько нужно работать, чтобы это купить.",
            "objects.custom.title": "Свой объект",
            "objects.custom.name": "Название",
            "objects.custom.price": "Цена",
            "objects.custom.sf_symbol": "SF Symbol",
            "objects.custom.image_picker": "Выбрать изображение",
            "objects.custom.change_image": "Сменить изображение",
            "objects.custom.image_hint": "Фото возьмётся из медиатеки и будет обрезано до квадратной иконки.",
            "objects.custom.image_error_title": "Изображение недоступно",
            "objects.custom.image_error": "Не удалось загрузить это изображение. Попробуйте другое фото.",
            "objects.custom.save_error": "Не удалось сохранить изображение на устройстве.",
            "objects.custom.manage_title": "Свои объекты",
            "objects.custom.manage_hint": "Перетаскивайте для смены порядка. Смахните влево или нажмите Delete, чтобы удалить объект.",
            "objects.custom.edit_title": "Изменить объект",
            "objects.custom.update": "Обновить объект",
            "objects.custom.save": "Сохранить объект",
            "objects.custom.default_name": "Свой объект",
            "objects.custom.supporting_line": "Пользовательский ориентир для сравнения с зарплатой.",
            "work.title": "Почувствуйте цену в часах труда.",
            "work.subtitle": "Временные дорожки превращают цену в реальное усилие.",
            "work.share.title": "Столько вы работаете ради",
            "work.share.subtitle": "%@ часов работы",
            "cities.subtitle": "Локальные редакционные индексы, а не обещания точности по налогам.",
            "cities.search": "Поиск города или страны",
            "cities.sort": "Сортировка",
            "cities.pin": "Закрепить",
            "cities.stretch_score": "Индекс растяжки %@",
            "cities.daily_power_value": "Покупательная сила в день: %@",
            "cities.burger_pace": "Бургеров в час: %@",
            "cities.pressure_index": "Индекс давления: %@",
            "cities.daily_power": "Покупательная сила в день: %@",
            "cities.housing_pressure": "Жилищная нагрузка: %@",
            "cities.tech_affordability_score": "Доступность техники: %@",
            "cities.big_mac_pace": "Big Mac в час: %@",
            "cities.affordability": "Доступность",
            "cities.method": "Метод",
            "cities.method_note": "Статичный локальный набор данных. Редакционные индексы накладываются на ваш сохранённый сценарий без притворной налоговой точности.",
            "cities.share_city_card": "Поделиться карточкой города",
            "gap.subtitle": "Жёстко, по фактам и пригодно для шаринга без дешёвой драматизации.",
            "gap.comparator_pace": "Темп сравнения",
            "gap.comparator_pace_subtitle": "Относительная скорость минута к минуте",
            "gap.they_earn_your_hour_in": "Они зарабатывают ваш час за",
            "gap.they_earn_your_hour_in_subtitle": "Сжатый перевод разницы во времени",
            "gap.delta_per_hour": "Разница в час",
            "gap.delta_per_hour_subtitle": "Разрыв при одинаковых рабочих допущениях",
            "gap.ladder": "Лестница разрыва",
            "gap.ladder_body": "%@ зарабатывает эквивалент %@ PS5-часов экономии за каждый час работы.",
            "gap.empty_title": "Добавьте зарплату для сравнения в допущениях, чтобы открыть этот экран.",
            "gap.empty_body": "Используйте его для босса, другого оффера, целевой зарплаты или любого бенчмарка, с которым хотите сравнивать свой текущий темп.",
            "gap.share.title": "Темп сравнения",
            "gap.share.subtitle": "%@ против вашего текущего сценария",
            "gap.share.annual": "Годовой доход для сравнения: %@",
            "gap.share.delta": "Разница в час: %@",
            "gap.share.minutes": "Они зарабатывают ваш час за %@ минут",
            "library.title": "Библиотека сценариев",
            "library.current": "Текущий",
            "library.archive": "В архив",
            "library.duplicate": "Дублировать",
            "library.compare": "Сравнить",
            "library.city_rent": "Город: %@  Аренда: %@",
            "library.delta_annual": "Разница: %@ в год",
            "library.rent_difference": "Разница по аренде: %@ в месяц",
            "scenario.current_role": "Текущая роль",
            "scenario.manager": "Менеджер",
            "scenario.comparator": "Сравнение",
            "scenario.new": "Новый сценарий",
            "scenario.copy_format": "Копия %@",
            "share.title": "Share Studio",
            "share.template": "Шаблон",
            "share.privacy": "Приватность",
            "share.export_card": "Экспортировать карточку",
            "share.export_note": "Экспорт изображения использует нативный рендеринг с активной темой и выбранным режимом приватности.",
            "share_privacy.exact": "Точно",
            "share_privacy.blurred": "Размыто",
            "share_privacy.hidden": "Скрыто",
            "share_privacy.hidden_value": "Скрыто",
            "share_template.bold_number": "Крупное число",
            "share_template.comparison_split": "Сравнение пополам",
            "share_template.city_ranking": "Рейтинг городов",
            "share_template.object_statement": "Объект как тезис",
            "share_template.work_time": "Время работы",
            "share_template.summary_set": "Набор сводок",
            "assumptions.calculation_basis": "База расчёта",
            "assumptions.manual_take_home_annual": "Годовой доход на руки вручную",
            "assumptions.hours_per_week": "Часов в неделю",
            "assumptions.weeks_per_year": "Недель в году",
            "assumptions.paychecks_per_year": "Выплат в год: %@",
            "assumptions.paychecks_per_year_label": "Выплат в год",
            "assumptions.work_schedule": "График работы",
            "assumptions.monthly_rent": "Аренда в месяц",
            "assumptions.comparator_salary": "Годовая зарплата для сравнения",
            "assumptions.comparator_label": "Подпись сравнения",
            "assumptions.home_city": "Базовый город",
            "assumptions.lifestyle_inputs": "Бытовые параметры",
            "onboarding.page1.title": "Поймите, что реально значит ваша зарплата.",
            "onboarding.page1.subtitle": "Переводите доход во время, предметы, аренду и повседневный контекст.",
            "onboarding.page1.stat": "$0.43 / мин",
            "onboarding.page1.label": "Кофе за 18.4 минуты",
            "onboarding.page2.title": "Узнайте, сколько вещи стоят по-настоящему.",
            "onboarding.page2.subtitle": "Переведите любую покупку в часы вашей жизни.",
            "onboarding.page2.stat": "6.2 ч",
            "onboarding.page2.label": "PS5 стоит вам 6.2 часа работы",
            "onboarding.page3.title": "Сравните зарплату в 50 городах.",
            "onboarding.page3.subtitle": "Поймите, где та же сумма тянется дальше.",
            "onboarding.page3.stat": "в 3 раза дальше",
            "onboarding.page3.label": "Та же зарплата: Остин против Сан-Франциско",
            "onboarding.page4.title": "Приватность по умолчанию.",
            "onboarding.page4.subtitle": "Все расчёты остаются на вашем устройстве. Аккаунт не нужен.",
            "onboarding.page4.stat": "100% локально",
            "onboarding.page4.label": "Ни один байт не уходит с устройства",
            "onboarding.cta.finish": "Перевести мою зарплату",
            "work_desc.coffee_break": "Меньше, чем кофейный перерыв",
            "work_desc.lunch_stretch": "Примерно как длинный обед",
            "work_desc.focus_block": "Часть сфокусированного рабочего блока",
            "work_desc.half_day": "Примерно полдня работы",
            "work_desc.more_than_day": "Больше одного полного дня",
            "work_desc.week": "Почти рабочая неделя",
            "work_desc.serious_chunk": "Серьёзный кусок рабочего времени",
            "city_comparison.stretches_further": "Здесь зарплата тянется дальше.",
            "city_comparison.feels_tighter": "Здесь по ощущениям теснее.",
            "city_comparison.saved_assumptions": "На основе сохранённых допущений."
        ],
        "th": [
            "settings.language": "ภาษา",
            "settings.language.system": "ตามระบบ",
            "settings.appearance": "รูปลักษณ์",
            "settings.theme": "ธีม",
            "settings.reduce_motion": "ลดการเคลื่อนไหว",
            "settings.haptics": "การสั่นตอบสนอง",
            "settings.high_contrast": "คอนทราสต์สูง",
            "common.edit": "แก้ไข",
            "common.done": "เสร็จสิ้น",
            "settings.defaults": "ค่าเริ่มต้น",
            "settings.default_currency": "สกุลเงินเริ่มต้น",
            "settings.income_basis": "ฐานรายได้",
            "settings.dataset_info": "ข้อมูลชุดข้อมูล",
            "settings.version": "เวอร์ชัน",
            "settings.cities_bundled": "จำนวนเมืองในชุดข้อมูล",
            "settings.objects_bundled": "จำนวนออบเจกต์ในชุดข้อมูล",
            "settings.dataset_note": "ดัชนีเมืองและราคาสิ่งของเป็นข้อมูลอ้างอิงท้องถิ่นแบบคงที่ ใช้เพื่อทำให้สมมติฐานชัดขึ้น ไม่ได้อ้างว่าเป็นความจริงทางเศรษฐกิจแบบเบ็ดเสร็จ",
            "settings.privacy": "ความเป็นส่วนตัว",
            "settings.privacy_note": "Earnza ทำงานออฟไลน์เต็มรูปแบบ ไม่ต้องมีบัญชี ไม่มีการติดตาม และไม่พึ่งพาเซิร์ฟเวอร์สำหรับการใช้งานหลัก",
            "salary_input.annual": "รายปี",
            "salary_input.monthly": "รายเดือน",
            "salary_input.weekly": "รายสัปดาห์",
            "salary_input.hourly": "รายชั่วโมง",
            "salary_input.currency": "สกุลเงิน",
            "salary_input.input_mode": "รูปแบบการกรอก",
            "salary_input.based_on": "อิงตามการกรอกแบบ %@ และสมมติฐานการทำงานที่บันทึกไว้",
            "salary_input.edit_assumptions": "แก้ไขสมมติฐาน",
            "income_basis.gross": "ก่อนหักภาษี",
            "income_basis.take_home": "เงินสุทธิ",
            "theme.light": "สว่าง",
            "theme.dark": "มืด",
            "theme.solar": "Solar",
            "theme.mono": "Mono",
            "canvas.live": "เรียลไทม์",
            "canvas.objects": "สิ่งของ",
            "canvas.work": "งาน",
            "canvas.cities": "เมือง",
            "canvas.gap": "ช่องว่าง",
            "header.scenario": "สถานการณ์",
            "header.share": "แชร์",
            "header.settings": "การตั้งค่า",
            "assumption.hours": "ชั่วโมง",
            "assumption.weeks": "สัปดาห์",
            "assumption.rent": "ค่าเช่า",
            "assumption.comparator": "ตัวเทียบ",
            "assumption.city": "เมือง",
            "assumption.basis": "ฐาน",
            "pace.per_month": "ต่อเดือน",
            "pace.per_day": "ต่อวัน",
            "pace.per_hour": "ต่อชั่วโมง",
            "pace.per_minute": "ต่อนาที",
            "pace.per_second": "ต่อวินาที",
            "pace.per_workday": "ต่อวันทำงาน",
            "pace.per_paycheck": "ต่อรอบจ่ายเงิน",
            "common.off": "ปิด",
            "common.unset": "ยังไม่ได้ตั้ง",
            "common.value": "ค่า",
            "common.you": "คุณ",
            "common.scenario_value": "สถานการณ์: %@",
            "common.currency_value": "สกุลเงิน: %@",
            "common.exact_value": "ค่าจริง: %@",
            "common.price_value": "ราคา: %@",
            "common.share_card": "แชร์การ์ด",
            "common.currency": "สกุลเงิน",
            "common.ok": "ตกลง",
            "share.default.subtitle": "นี่คือจำนวนเงินที่คุณหาได้ในหนึ่งนาที",
            "share.default.hourly_pace": "อัตราต่อชั่วโมง: %@",
            "share.default.monthly_pace": "อัตราต่อเดือน: %@",
            "share.default.assumptions": "อิงจาก %@ ชม./สัปดาห์ และ %@ สัปดาห์/ปี",
            "live.title": "ดูให้เห็นว่ารายได้กลายเป็นของจริง",
            "live.subtitle": "ดูอัตรารายได้ต่อเนื่อง ยอดสะสมระหว่างการใช้งาน และช่วงเวลาที่พร้อมแชร์ได้ทันที",
            "live.earning_now": "ตอนนี้คุณกำลังหาเงินอยู่",
            "live.real_time_note": "ขณะที่คุณกำลังดูอยู่ ตัวเลขนี้ยังเพิ่มขึ้นแบบเรียลไทม์",
            "live.minute_pace": "อัตราต่อนาที",
            "live.while_you_read_this": "ระหว่างที่คุณกำลังอ่าน",
            "live.screen_session": "ยอดสะสมในเซสชันนี้",
            "live.per_minute_value": "ต่อนาที: %@",
            "live.per_hour_value": "ต่อชั่วโมง: %@",
            "live.per_second_subtitle": "อัตราต่อเนื่องสำหรับตัวนับสด",
            "live.per_minute_subtitle": "จังหวะที่เข้าใจง่ายที่สุดแบบเรียลไทม์",
            "live.per_workday_subtitle": "อิงตามสมมติฐานการทำงานที่บันทึกไว้",
            "live.per_paycheck_subtitle": "อิงตามจำนวนรอบจ่ายต่อปี",
            "live.per_month_subtitle": "กระจายเงินเดือนออกเป็น 12 เดือน",
            "live.reading_session": "เซสชันการใช้งาน",
            "live.reading_session_subtitle": "รีเซ็ตเมื่อแอปกลับมาแอ็กทีฟอีกครั้ง",
            "live.milestones": "หลักหมาย",
            "live.cross_milestone": "ผ่าน %@ ให้ได้ในเซสชันนี้",
            "objects.title": "แปลงเงินเดือนให้เป็นสิ่งของจริง",
            "objects.subtitle": "ออบเจกต์ยังคงแก้ไขได้ อิงบริบทท้องถิ่น และแชร์ต่อได้ทันที",
            "objects.mode": "โหมด",
            "objects.mode.how_many": "ซื้อได้กี่ชิ้น",
            "objects.mode.work_for_it": "ต้องทำงานเท่าไร",
            "objects.add_custom": "เพิ่มออบเจกต์เอง",
            "objects.quantity_note": "จำนวนที่คุณหาได้ตามอัตราปัจจุบัน",
            "objects.favorite": "รายการโปรด",
            "objects.per_hour": "%@ ต่อชั่วโมง",
            "objects.per_day": "ต่อวัน: %@",
            "objects.workdays": "%@ วันทำงาน",
            "objects.hours": "%@ ชม.",
            "objects.minutes": "%@ นาที",
            "objects.work_months": "%@ เดือนงาน",
            "objects.work_years": "%@ ปีงาน",
            "objects.hero_earn": "คุณหา %@ %@ ต่อชั่วโมง",
            "objects.hero_work": "%@ หนึ่งชิ้นใช้เวลางาน %@ ชั่วโมง",
            "objects.hero_work_duration": "%@ หนึ่งชิ้น ≈ ทำงาน %@",
            "objects.share.earn_subtitle": "ตอนนี้คุณหาได้กี่ชิ้นตามอัตราปัจจุบัน",
            "objects.share.work_subtitle": "ต้องทำงานนานแค่ไหนถึงจะได้มันมา",
            "objects.custom.title": "ออบเจกต์ของฉัน",
            "objects.custom.name": "ชื่อ",
            "objects.custom.price": "ราคา",
            "objects.custom.sf_symbol": "SF Symbol",
            "objects.custom.image_picker": "เลือกรูปภาพ",
            "objects.custom.change_image": "เปลี่ยนรูปภาพ",
            "objects.custom.image_hint": "เลือกรูปจากคลัง รูปจะถูกครอปเป็นไอคอนสี่เหลี่ยมจัตุรัส",
            "objects.custom.image_error_title": "ไม่สามารถใช้รูปภาพนี้ได้",
            "objects.custom.image_error": "โหลดรูปนี้ไม่ได้ ลองใช้รูปอื่น",
            "objects.custom.save_error": "บันทึกรูปนี้ลงอุปกรณ์ไม่สำเร็จ",
            "objects.custom.manage_title": "แก้ไขออบเจกต์แบบกำหนดเอง",
            "objects.custom.manage_hint": "ลากเพื่อจัดลำดับใหม่ ปัดซ้ายหรือแตะ Delete เพื่อลบออบเจกต์",
            "objects.custom.edit_title": "แก้ไขออบเจกต์",
            "objects.custom.update": "อัปเดตออบเจกต์",
            "objects.custom.save": "บันทึกออบเจกต์",
            "objects.custom.default_name": "ออบเจกต์ของฉัน",
            "objects.custom.supporting_line": "เกณฑ์เทียบเงินเดือนที่คุณกำหนดเอง",
            "work.title": "มองราคาเป็นชั่วโมงทำงาน",
            "work.subtitle": "เลนเวลาช่วยแปลงราคาให้กลายเป็นแรงที่ต้องใช้จริง",
            "work.share.title": "คุณต้องทำงานนานเท่านี้เพื่อสิ่งนี้",
            "work.share.subtitle": "ใช้เวลาทำงาน %@ ชั่วโมง",
            "cities.subtitle": "ดัชนีเชิงบรรณาธิการแบบท้องถิ่น ไม่ใช่คำสัญญาเรื่องภาษี",
            "cities.search": "ค้นหาเมืองหรือประเทศ",
            "cities.sort": "เรียงลำดับ",
            "cities.pin": "ปักหมุด",
            "cities.stretch_score": "คะแนนความยืดหยุ่น %@",
            "cities.daily_power_value": "กำลังซื้อรายวัน: %@",
            "cities.burger_pace": "เบอร์เกอร์ต่อชั่วโมง: %@",
            "cities.pressure_index": "ดัชนีความกดดัน: %@",
            "cities.daily_power": "กำลังซื้อรายวัน: %@",
            "cities.housing_pressure": "แรงกดดันด้านที่อยู่อาศัย: %@",
            "cities.tech_affordability_score": "คะแนนการเข้าถึงเทคโนโลยี: %@",
            "cities.big_mac_pace": "Big Mac ต่อชั่วโมง: %@",
            "cities.affordability": "ความสามารถในการจ่าย",
            "cities.method": "วิธีคำนวณ",
            "cities.method_note": "ใช้ชุดข้อมูลท้องถิ่นแบบคงที่ ดัชนีเชิงบรรณาธิการจะถูกนำไปใช้กับสถานการณ์ที่คุณบันทึกไว้โดยไม่แกล้งทำว่าแม่นภาษีทุกจุด",
            "cities.share_city_card": "แชร์การ์ดเมือง",
            "cities.best_city_intro": "เงินเดือนของคุณไปได้ไกลที่สุดที่",
            "cities.burgers_per_hour": "%@ เบอร์เกอร์/ชม.",
            "city_sort.best_stretch": "ยืดได้คุ้มสุด",
            "city_sort.closest_match": "ใกล้เคียงสุด",
            "city_sort.daily_power": "กำลังซื้อรายวัน",
            "city_sort.housing_ratio": "สัดส่วนที่อยู่อาศัย",
            "city_sort.lifestyle_pressure": "แรงกดดันด้านไลฟ์สไตล์",
            "city_sort.tech_affordability": "การเข้าถึงเทคโนโลยี",
            "gap.subtitle": "ตรงไปตรงมา ดูจากข้อเท็จจริง และแชร์ได้โดยไม่ดราม่าเกินจริง",
            "gap.comparator_pace": "อัตราของตัวเทียบ",
            "gap.comparator_pace_subtitle": "ความเร็วสัมพัทธ์แบบนาทีต่อนาที",
            "gap.they_earn_your_hour_in": "เขาใช้เวลาเท่านี้เพื่อหาเท่ากับหนึ่งชั่วโมงของคุณ",
            "gap.they_earn_your_hour_in_subtitle": "แปลช่องว่างออกมาเป็นเวลาแบบสั้นกระชับ",
            "gap.delta_per_hour": "ส่วนต่างต่อชั่วโมง",
            "gap.delta_per_hour_subtitle": "ช่องว่างเมื่อใช้สมมติฐานการทำงานเดียวกัน",
            "gap.ladder": "บันไดช่องว่าง",
            "gap.ladder_body": "%@ เทียบเท่ากับการประหยัดเวลาทำงานเพื่อซื้อ PS5 ได้ %@ ชั่วโมงในทุกชั่วโมงที่ทำงาน",
            "gap.empty_title": "เพิ่มเงินเดือนสำหรับเปรียบเทียบในสมมติฐานเพื่อปลดล็อกหน้าจอนี้",
            "gap.empty_body": "ใช้ได้กับหัวหน้า ข้อเสนองานใหม่ เงินเดือนเป้าหมาย หรือเกณฑ์อ้างอิงอะไรก็ได้ที่คุณอยากเทียบกับจังหวะรายได้ปัจจุบัน",
            "gap.share.title": "อัตราของตัวเทียบ",
            "gap.share.subtitle": "%@ เทียบกับสถานการณ์ปัจจุบันของคุณ",
            "gap.share.annual": "รายได้ต่อปีของตัวเทียบ: %@",
            "gap.share.delta": "ส่วนต่างต่อชั่วโมง: %@",
            "gap.share.minutes": "เขาใช้เวลา %@ นาทีเพื่อหาเท่ากับหนึ่งชั่วโมงของคุณ",
            "library.title": "คลังสถานการณ์",
            "library.current": "ปัจจุบัน",
            "library.archive": "เก็บถาวร",
            "library.duplicate": "ทำสำเนา",
            "library.compare": "เปรียบเทียบ",
            "library.city_rent": "เมือง: %@  ค่าเช่า: %@",
            "library.delta_annual": "ส่วนต่าง: %@ ต่อปี",
            "library.rent_difference": "ส่วนต่างค่าเช่า: %@ ต่อเดือน",
            "scenario.current_role": "บทบาทปัจจุบัน",
            "scenario.manager": "ผู้จัดการ",
            "scenario.comparator": "ตัวเทียบ",
            "scenario.new": "สถานการณ์ใหม่",
            "scenario.copy_format": "สำเนา %@",
            "share.title": "การแชร์",
            "share.template": "เทมเพลต",
            "share.privacy": "ความเป็นส่วนตัว",
            "share.export_card": "ส่งออกการ์ด",
            "share.export_note": "การส่งออกภาพนิ่งใช้การเรนเดอร์แบบเนทีฟ พร้อมธีมที่กำลังใช้อยู่และการตั้งค่าความเป็นส่วนตัวที่เลือกไว้",
            "share_privacy.exact": "แสดงจริง",
            "share_privacy.blurred": "เบลอ",
            "share_privacy.hidden": "ซ่อน",
            "share_privacy.hidden_value": "ซ่อน",
            "share_template.bold_number": "ตัวเลขเด่น",
            "share_template.comparison_split": "เทียบแบบแบ่งครึ่ง",
            "share_template.city_ranking": "อันดับเมือง",
            "share_template.object_statement": "ออบเจกต์เป็นประเด็น",
            "share_template.work_time": "เวลางาน",
            "share_template.summary_set": "ชุดสรุป",
            "assumptions.calculation_basis": "ฐานการคำนวณ",
            "assumptions.manual_take_home_annual": "กรอกรายได้สุทธิต่อปีเอง",
            "assumptions.hours_per_week": "ชั่วโมงต่อสัปดาห์",
            "assumptions.weeks_per_year": "สัปดาห์ต่อปี",
            "assumptions.paychecks_per_year": "จำนวนรอบจ่ายต่อปี: %@",
            "assumptions.paychecks_per_year_label": "จำนวนรอบจ่ายต่อปี",
            "assumptions.work_schedule": "ตารางการทำงาน",
            "assumptions.monthly_rent": "ค่าเช่าต่อเดือน",
            "assumptions.comparator_salary": "เงินเดือนต่อปีของตัวเทียบ",
            "assumptions.comparator_label": "ป้ายชื่อของตัวเทียบ",
            "assumptions.home_city": "เมืองหลัก",
            "assumptions.lifestyle_inputs": "ตัวแปรการใช้ชีวิต",
            "onboarding.page1.title": "ทำให้เห็นชัดว่าเงินเดือนของคุณหมายความว่าอะไร",
            "onboarding.page1.subtitle": "แปลงรายได้ให้เป็นเวลา สิ่งของ ค่าเช่า และบริบทชีวิตจริง",
            "onboarding.page1.stat": "$0.43 / นาที",
            "onboarding.page1.label": "กาแฟใน 18.4 นาที",
            "onboarding.page2.title": "รู้ให้ชัดว่าของแต่ละอย่างกินเวลาชีวิตคุณเท่าไร",
            "onboarding.page2.subtitle": "แปลงทุกการซื้อให้เป็นชั่วโมงจากชีวิตของคุณ",
            "onboarding.page2.stat": "6.2 ชม.",
            "onboarding.page2.label": "PS5 ทำให้คุณใช้เวลางาน 6.2 ชั่วโมง",
            "onboarding.page3.title": "เทียบรายได้ของคุณใน 50 เมือง",
            "onboarding.page3.subtitle": "ดูว่าเงินก้อนเดียวกันไปได้ไกลกว่าที่ไหน",
            "onboarding.page3.stat": "ไกลขึ้น 3 เท่า",
            "onboarding.page3.label": "เงินเดือนเท่าเดิม: ออสติน เทียบกับ ซานฟรานซิสโก",
            "onboarding.page4.title": "ออกแบบมาให้เป็นส่วนตัวตั้งแต่แรก",
            "onboarding.page4.subtitle": "การคำนวณทั้งหมดอยู่บนอุปกรณ์ของคุณ ไม่ต้องมีบัญชี",
            "onboarding.page4.stat": "100% บนอุปกรณ์",
            "onboarding.page4.label": "ไม่มีข้อมูลแม้แต่ไบต์เดียวออกจากเครื่อง",
            "onboarding.cta.finish": "เริ่มแปลเงินเดือนของฉัน",
            "work_desc.coffee_break": "น้อยกว่าช่วงพักกาแฟ",
            "work_desc.lunch_stretch": "พอ ๆ กับช่วงพักกลางวันยาว ๆ",
            "work_desc.focus_block": "เป็นส่วนหนึ่งของช่วงทำงานที่โฟกัสจริงจัง",
            "work_desc.half_day": "ประมาณครึ่งวันทำงาน",
            "work_desc.more_than_day": "มากกว่าหนึ่งวันเต็ม",
            "work_desc.week": "เกือบเท่าหนึ่งสัปดาห์ทำงาน",
            "work_desc.serious_chunk": "กินเวลางานไปพอสมควร",
            "city_comparison.stretches_further": "เงินก้อนนี้ไปได้ไกลกว่าที่นี่",
            "city_comparison.feels_tighter": "เมืองนี้ตึงมือกว่าชัดเจน",
            "city_comparison.saved_assumptions": "อิงจากสมมติฐานที่บันทึกไว้",
            "object_category.bills": "บิล",
            "object_category.custom": "กำหนดเอง",
            "object_category.food": "อาหาร",
            "object_category.housing": "ที่อยู่อาศัย",
            "object_category.lifestyle": "ไลฟ์สไตล์",
            "object_category.tech": "เทคโนโลยี",
            "object_category.transport": "การเดินทาง",
            "object_category.travel": "ท่องเที่ยว",
            "object.big_mac.name": "บิกแมค",
            "object.coffee.name": "กาแฟ",
            "object.grocery_basket.name": "ตะกร้าของชำ",
            "object.ps5.name": "PS5",
            "object.iphone.name": "iPhone",
            "object.airpods.name": "AirPods Pro",
            "object.rent_day.name": "ค่าเช่าหนึ่งวัน",
            "object.streaming.name": "ค่าสตรีมมิงหนึ่งเดือน",
            "object.cinema.name": "ตั๋วหนัง",
            "object.flight.name": "เที่ยวบินระหว่างเมือง",
            "object.sneakers.name": "รองเท้าผ้าใบ",
            "object.gym.name": "สมาชิกฟิตเนส",
            "object.taxi.name": "ค่าแท็กซี่หนึ่งเที่ยว",
            "object.energy_bill.name": "ค่าสาธารณูปโภคส่วนหนึ่ง",
            "object.big_mac.line": "เกณฑ์เร็ว ๆ สำหรับวัดกำลังซื้อในชีวิตประจำวัน",
            "object.coffee.line": "ความสุขเล็ก ๆ ที่เกิดขึ้นซ้ำและเห็นภาพได้ทันที",
            "object.grocery_basket.line": "ค่าใช้จ่ายสำหรับตะกร้าของชำหนึ่งรอบ",
            "object.ps5.line": "ตัวชี้วัดที่ชัดสำหรับการใช้จ่ายก้อนเดียวแบบฟุ่มเฟือย",
            "object.iphone.line": "หมุดอ้างอิงของเทคโนโลยีระดับพรีเมียม",
            "object.airpods.line": "ของฟุ่มเฟือยชิ้นเล็กที่ทุกคนพอนึกมูลค่าออก",
            "object.rent_day.line": "แรงกดดันเรื่องที่อยู่อาศัยในหนึ่งวัน",
            "object.streaming.line": "ค่าสมัครบริการรายเดือนที่คุ้นเคย",
            "object.cinema.line": "เกณฑ์เล็ก ๆ สำหรับการใช้จ่ายเพื่อพักผ่อน",
            "object.flight.line": "ค่าหนีเมืองแบบรวดเร็ว",
            "object.sneakers.line": "ของสายสไตล์ที่คนทั่วไปเข้าถึงได้",
            "object.gym.line": "ค่าใช้จ่ายประจำสำหรับรูทีนรายเดือน",
            "object.taxi.line": "การแลกความสะดวกกับเวลา",
            "object.energy_bill.line": "จังหวะค่าใช้จ่ายสาธารณูปโภครายเดือนในบ้าน",
            "city.new_york.note": "รายได้สูง แต่แรงกดดันก็สูง",
            "city.berlin.note": "ค่าครองชีพสมดุล พร้อมขนส่งสาธารณะที่ดี",
            "city.warsaw.note": "เมืองที่เงินเดือนไปได้คุ้มมาก"
        ]
    ]
}

extension Scenario {
    static var localizedStarterName: String {
        L10n.s("scenario.current_role", "Current Role")
    }

    static var localizedStarterComparator: String {
        L10n.s("scenario.manager", "Manager")
    }

    static var localizedComparatorFallback: String {
        L10n.s("scenario.comparator", "Comparator")
    }

    static var localizedNewScenarioName: String {
        L10n.s("scenario.new", "New Scenario")
    }

    static func localizedDuplicateName(from name: String) -> String {
        L10n.f("scenario.copy_format", "%@ Copy", name)
    }
}
